### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by s-bt** [skahwah/SQLRecon#15]
Hey there,

first things first: Great tool :)
I would suggest the following features to make it even better:

- output to json file
- ability to use credentials for sqlspns, as the tool might be run on a non domain joined machine
- a new module (e.g. audit) that runs commands automatically (like PowerUpSQL) to have a single parameter for running all necessary non-intrusive checks with a json output to process the results

Cheers

**Comment by skahwah** [comment]
Thanks for your suggestion! Here are some answers for you:

- A design decision has been made to standardize all output to markdown via console output, and not writing files to disk is intentional due to operation security considerations.
- I'm considering ading credential support for sqlspns, but to be honest, C2 features like "steal token", or "make token" already solve this problem. Along with net use on Windows.
- The audit module idea is interesting, I'm not familiar with how it works, but if you are, feel free to make a pull request!
